#############################################################################
# Makefile for building: libmtp.so
# Generated by HivOS
# Project:  multi touch panel  Linux library
# Template: lib
# ###########################################################################
#
# ##### Compiler, tools and options

CURDIR =.
-include $(BUDIR)/rules.mk


ARFLAGS = rcv



ifdef $(ARCH_ARM)
VPATH := arm
else
VPATH := pc
endif


INCDIR := $(VPATH)/include/
LIBDIR := $(VPATH)/libs/

TOOLCHAININCDIR:=$(HIVEOS)/include/
TOOLCHAINLIBDIR:=$(HIVEOS)/lib/

SHLD = ${CC} ${CFLAGS}
LDSHFLAGS = -shared -Wl,-Bsymbolic  -Wl,-rpath -Wl,/usr/lib -Wl,-rpath,/usr/lib
LIBS      = -L./ -lm -lz -lstdc++ -lpthread -lzint

CFLAGS += -I/home/lilj/work/zint-2.8.0/arm/include
CXXFLAGS += -I/home/lilj/work/zint-2.8.0/arm/include

SOURCE := $(wildcard ./*.cpp)
OBJS := $(patsubst %.cpp, %.o, $(SOURCE))

INC_FILES := qrcode.h

LIBSHARED := libqrcode.so
LFLAGS    :=  -Wl,-O2 -shared -Wl,-soname,$(LIBSHARED)
LDFLAGS += -L/home/lilj/work/zint-2.8.0/arm/lib

first: all 

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	        $(CXX) -c $(CXXFLAGS) -o "$@" "$<"

.cc.o:
	        $(CXX) -c $(CXXFLAGS) -o "$@" "$<"

.cxx.o:
	        $(CXX) -c $(CXXFLAGS) -o "$@" "$<"

.C.o:
	        $(CXX) -c $(CXXFLAGS) -o "$@" "$<"

.c.o:
	        $(CC) -c $(CFLAGS) -o "$@" "$<"

all:	$(LIBSHARED)

$(LIBSHARED):	$(OBJS)
	@$(LINK) $(LFLAGS) $(LDFLAGS) -o $(LIBSHARED) $(OBJS) $(LIBS)
	@($(STRIP) $@)
#	@($(COPY) $@ $(LIBDIR))
#	@($(COPY) $@ $(TOOLCHAINLIBDIR))
#	@($(COPY) $(INC_FILES) $(INCDIR))
#	@($(COPY) $(INC_FILES) $(TOOLCHAININCDIR))

clean:
	$(DELETE) $(OBJS) $(LIBSHARED)
	
.PHONY : clean all
